# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: excap/plazaroute-ci
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - plazarouting-dependencies-{{ checksum "plaza_routing/requirements.txt" }}
          - plazapreprocessing-dependencies-{{ checksum "plaza_preprocessing/requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r plaza_preprocessing/requirements.txt
            pip install -r plaza_preprocessing/requirements-dev.txt
            pip install -r plaza_routing/requirements.txt
            pip install -r plaza_routing/requirements-dev.txt

      - save_cache:
          paths:
            - ./venv
          key: plazarouting-dependencies-{{ checksum "plaza_routing/requirements.txt" }}
        
      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pip install --editable plaza_routing/
            pytest plaza_routing
            pip install --editable plaza_preprocessing/
            pytest plaza_preprocessing

      # - store_artifacts:
      #     path: test-reports
      #     destination: test-reports
          