version: '3'
services:
  nginx:
    image: nginx:1.13.7-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 5000:80
    links:
      - plaza_routing

  plaza_routing:
    build: plaza_routing/
    links:
      - graphhopper

  graphhopper:
    build: graphhopper/
    volumes:
      - ./gh-data:/gh-data
    environment:
      JETTY_PORT: 8989
      JAVA_OPTS: "-server -Xconcurrentio -Xmx1g -Xms1g -XX:+UseG1GC -XX:MetaspaceSize=100M"
    entrypoint:
      - ./graphhopper.sh
      - web
      - /gh-data/switzerland-visibility-graph.pbf